#!/bin/bash

if [ $SOURCE_BRANCH != "master" ]; then
    JAVA_VERSION=$SOURCE_BRANCH
    MAJOR_VERSION=$(echo $JAVA_VERSION | cut -d . -f 1)
    if [ $MAJOR_VERSION -eq 1 ]; then
      MAJOR_VERSION=1.8.0
    fi
else
    JAVA_VERSION=
fi

echo "Building Java11 JDK $IMAGE_NAME"

docker build \
    --build-arg MAJOR_VERSION=$MAJOR_VERSION \
    --build-arg JAVA_VERSION=$JAVA_VERSION \
    -t $IMAGE_NAME .

echo "Building Java11 JRE $IMAGE_NAME-jre"

echo $MAJOR_VERSION - $JAVA_VERSION
docker build \
    --build-arg MAJOR_VERSION=$MAJOR_VERSION \
    --build-arg JAVA_VERSION=$JAVA_VERSION \
    --build-arg JAVA_DIST=headless \
    -t $IMAGE_NAME-jre .
