#!/bin/bash

if [ $SOURCE_BRANCH != "master" ]; then
    JAVA_VERSION=$SOURCE_BRANCH
else
    JAVA_VERSION=
fi

echo "Building Java11 JDK $IMAGE_NAME"

docker build \
    --build-arg JAVA_VERSION=$JAVA_VERSION \
    -t $IMAGE_NAME .

echo "Building Java11 JRE $IMAGE_NAME-jre"

docker build \
    --build-arg JAVA_VERSION=$JAVA_VERSION \
    --build-arg JAVA_DIST=headless \
    -t $IMAGE_NAME-jre .