#!/bin/bash

REPO_NAME=$(echo $IMAGE_NAME | cut -d ':' -f 1)

docker push $IMAGE_NAME-jre

for TAG in {11,openjdk-11}; do
    docker tag $IMAGE_NAME $REPO_NAME:$TAG
    docker push $REPO_NAME:$TAG
    docker tag $IMAGE_NAME-jre $REPO_NAME:$TAG-jre
    docker push $REPO_NAME:$TAG-jre
done